name: KnockbackSettings
description: "Edit your server's knockback settings per-world."
author: Cosmic5173
version: 1.0.0
api: 4.0.0
main: Cosmic5173\KnockbackSettings\Main

permissions:
  knockback.use:
    description: Grants access to view and change knockback settings.
    default: op